### ISSUE TITLE
--next

### ISSUE THREAD

**Issue by benmerckx** [lix-pm/haxeshim#1]
Seems like `-lib` parameters defined after `--next` are stripped, but not replaced.

**Comment by benmerckx** [comment]
I'm still noticing this... (haxeshim 0.5.4)

```
--macro Sys.println('before')
--next
-lib tink_core
-main Main
--interp
```

```
class Main {
	static function main()
		trace(tink.core.Noise.Noise);
}
```

```
before
Main.hx:3: characters 8-12 : Unknown identifier : tink
```

**Comment by back2dos** [comment]
This is very odd. The same code works for me.

What does `haxe --run resolve-args --macro Sys.println('before') --next -lib tink_core -main Main --interp` produce?

**Comment by benmerckx** [comment]
Ok, so the example seems to fail if run from a .hxml, as command line args it's fine.
```
$ haxe --run resolve-args build.hxml
-cp
/home/ben/haxe/haxelib/tink_core/1,6,1/src/
-D
tink_core=1.6.1
--run
resolve-args
--macro
Sys.println('before')
--next
-main
Main
--interp
```

```
$ haxe --run resolve-args --macro "Sys.println('before')" --next -lib tink_core -main Main --interp
--macro
Sys.println('before')
--next
-cp
/home/ben/haxe/haxelib/tink_core/1,6,1/src/
-D
tink_core=1.6.1
-main
Main
--interp
```

**Comment by back2dos** [comment]
I totally did not think about that ... *facepalm*

**Comment by back2dos** [comment]
Ok, I wrote a test for it and according to that I finally fixed it for good ;)
