### ISSUE TITLE
--cwd in *.hxml files isn't handled properly

### ISSUE THREAD

**Issue by sh-dave** [lix-pm/haxeshim#12]
Trying to build the attached project fails with haxeshim 0.9.0 (installed globally), but works with haxe 3.4.2.

```bash
d:\projects\hscwd>haxe build.hxml
Error: ENOENT: no such file or directory, open 'd:\projects\hscwd\build-js.hxml'
```
[hscwd.zip](https://github.com/lix-pm/haxeshim/files/1122356/hscwd.zip)

**Comment by back2dos** [comment]
Still haven't had time to run it against the project you supplied, but FWIW it should work better now.

**Comment by sh-dave** [comment]
seems to work fine 👍 will report back if i encounter issues in more complex projects
