### ISSUE TITLE
Error on npm install due to path confusion

### ISSUE THREAD

**Issue by Simn** [lix-pm/haxeshim#14]
```
C:\GitHub\haxe>npm -v
5.4.2

C:\GitHub\haxe>npm i haxeshim -g
C:\Users\simn\AppData\Roaming\npm\haxelib -> C:\Users\simn\AppData\Roaming\npm\node_modules\haxeshim\bin\haxelibshim.js
C:\Users\simn\AppData\Roaming\npm\haxe -> C:\Users\simn\AppData\Roaming\npm\node_modules\haxeshim\bin\haxeshim.js
C:\Users\simn\AppData\Roaming\npm\neko -> C:\Users\simn\AppData\Roaming\npm\node_modules\haxeshim\bin\nekoshim.js

> haxeshim@0.9.0 postinstall C:\Users\simn\AppData\Roaming\npm\node_modules\haxeshim
> node bin/postinstall.js

Error: Could not process argument show-version
invalid character: -
+ haxeshim@0.9.0
updated 1 package in 0.982s
```

```
C:\GitHub\haxe>where haxe
C:\GitHub\haxe\haxe.exe
C:\HaxeToolkit\4.0.0-preview.1\haxe\haxe.exe
C:\Users\simn\AppData\Roaming\npm\haxe
C:\Users\simn\AppData\Roaming\npm\haxe.cmd
C:\Users\simn\AppData\Roaming\npm\haxe.exe
```

Interestingly, it replaced the binaries in C:\HaxeToolkit\4.0.0-preview.1\haxe\, but not the ones in C:\GitHub\haxe\, which has higher priority. That's why it ends up calling my actual haxe.exe with haxeshim-specific arguments.

**Comment by kevinresol** [comment]
Actually I think that after installing haxeshim, the "haxe" executable inside the npm global bin directory should have highest priority. For me it looks like this (mac):

(note that `which haxe` points to `haxeshim.js`)

```
$ which haxe
/Users/kevin/.config/yarn/global/node_modules/.bin/haxe

$ ls -lah $(which haxe)
lrwxr-xr-x  1 kevin  staff    27B Sep 29 00:36 /Users/kevin/.config/yarn/global/node_modules/.bin/haxe -> ../haxeshim/bin/haxeshim.js
```

**Comment by kevinresol** [comment]
Oh well, just realized ([from readme](https://github.com/lix-pm/haxeshim#windows)) that on Windows it seems much more compilcated. Ignore my last comment.

**Comment by Simn** [comment]
I understand that path priority is difficult. What I don't understand is why it replaces the binaries only in a path that has "medium" priority.

**Comment by back2dos** [comment]
@Simn this check fails https://github.com/lix-pm/haxeshim/blob/master/src/haxeshim/PostInstall.hx#L92

The basic assumption here is that you got haxe through the installer (in which case those files exist) and I preferred not to touch anything "custom" because that seems like asking for trouble.

**Comment by Simn** [comment]
That's a reasonable decision. Still doesn't seem to make much sense to replace the "second best" path in that case, given that it will not be the one being executed.

**Comment by back2dos** [comment]
Well, if you have multiple haxe executables, it stands to reason that you're eventually going to delete one. If in your case it's the low prio one, then it doesn't really matter if anything was modified or not. If you delete the high prio one, you get the behavior that you most likely intended when installing haxeshim in the first place.

What would you consider the most sensible behavior in this situation?

**Comment by Simn** [comment]
I don't really want to waste your time with this because it likely only affects me and a couple other Haxe devs. Now that I know what the problem is, it's good enough to just work around it.

You _could_ add some warning for this situation so it's clearer what the problem is. But only do that if you have absolutely no other worries. ;)

**Comment by back2dos** [comment]
Well, I can't say it's high on my list, but we should do something eventually, so I'm going to keep this open.

**Comment by back2dos** [comment]
This should issue a relatively understandable warning now.
