### ISSUE TITLE
Pipe stdout/stderr of -cmd

### ISSUE THREAD

**Issue by benmerckx** [lix-pm/haxeshim#20]
Regular haxe will pipe output of `-cmd` to your terminal, while haxeshim doesn't seem to do so.

**Comment by benmerckx** [comment]
This must be https://github.com/HaxeFoundation/haxe/issues/6726, not haxeshim related

**Comment by back2dos** [comment]
I'll look into solving this on haxeshim's side. I wanted to add [`-cmd-detach`](https://github.com/HaxeFoundation/haxe/issues/6392) too anyway, so I'll just take care of both.

**Comment by back2dos** [comment]
Let's just make this Haxe's problem in the end ^^
