### ISSUE TITLE
Issue with nodejs > v10

### ISSUE THREAD

**Issue by cjhille** [lix-pm/haxeshim#27]
A few packages might need a recompile + publish to account for this hxnodejs issue:
https://github.com/HaxeFoundation/hxnodejs/issues/102

The current package won't run with nodejs >10.0.0 due to the improper check,
https://registry.npmjs.org/haxeshim/-/haxeshim-0.12.4.tgz

**Comment by back2dos** [comment]
I believe this now taken care of.
