### ISSUE TITLE
Neko on linux64

### ISSUE THREAD

**Issue by benmerckx** [lix-pm/haxeshim#3]
An install in a docker container (so no previous haxe installations) and then running haxelib gives me:
```
/root/haxe/versions/6899468/haxelib: error while loading shared libraries: libneko.so: cannot open shared object file: No such file or directory
```
Tested with 3.2.1 and nightly.

Is neko a dependency or should haxeshim manage installing it as well?

**Comment by back2dos** [comment]
Seeing how much Haxe stuff depends on neko (i.e. hxcpp, hxjava and hxcs) haxeshim should probably take care of installing it and also providing a neko command at the same time.

**Comment by back2dos** [comment]
Reminder to myself: http://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime

**Comment by back2dos** [comment]
Ok, haxeshim will now work if neko is installed in `<haxeshimPath>/neko`. The rest is for switchx to deal with.

**Comment by benmerckx** [comment]
This works! Is there a way to get a reference to the executable? I spawn a 'neko' process in one of my builds which obviously wouldn't work this way. Or maybe a command on switchx to get that global `<haxeshimPath>`?

**Comment by benmerckx** [comment]
Oh wait, that wouldn't work as neko is only installed if missing... So I'm really looking for a way to find neko's location whether installed prevously or through switchx :)

**Comment by back2dos** [comment]
Uhm, what about letting haxeshim expose a neko command?

**Comment by benmerckx** [comment]
That'd be great, and useful for others expecting neko to work after installing switchx.
