### ISSUE TITLE
Remove the file watcher?

### ISSUE THREAD

**Issue by Gama11** [lix-pm/haxeshim#42]
As far as I can tell, the `.haxerc` file watcher is not needed anymore with the lix extension. I also can't think of a reason to use lix with VSCode without the lix extension.

In fact, it only seems to lead to issues, such as the server sometimes crashing just before the lix extension can update vshaxe's Haxe executable:

![](https://i.imgur.com/Yjd0S7U.png)

I'm guessing this doesn't always happen because there's a race condition here (the lix extension also has a file watcher for the `.haxerc` file).

**Comment by back2dos** [comment]
Yeah, this is a problem, but I prefer a solution that doesn't make this a vscode-only thing, e.g. a pokemon clause in the watcher callback.
