### ISSUE TITLE
multiple target hxml file

### ISSUE THREAD

**Issue by varadig** [lix-pm/haxeshim#45]
I have 3 html file.
one for dependencies one for global parameters and one for multiple js target.

dependencies.hxml
```
-lib angular.haxe
-lib gotocore-hx
-lib haxe-crypto
-lib materialize.hx
-lib compiletime
-lib random
```

global.hxml
```
dependencies.hxml
-cp src
-dce no
```

build.hxml
```
global.hxml
-main admin.AdminApp
-js ../www/public/js/app/AdminApp.js
--next
global.hxml
-main company.CompanyApp
-js ../www/public/js/app/CompanyApp.js
--next
global.hxml
-main user.UserApp
-js ../www/public/js/app/UserApp.js
```

the haxe_libraries is contained all the dependencies:

```
haxe_libraries/angular.haxe.hxml
haxe_libraries/compiletime.hxml
haxe_libraries/gotocore-hx.hxml
haxe_libraries/haxe-crypto.hxml
haxe_libraries/materialize.hx.hxml
haxe_libraries/random.hxml

```

but on `haxe build.hxml` I got:

`src/company/CompanyApp.hx:2: characters 7-22 : Type not found : angular.Angular`

If the build.hxml just contains just the CompanyApp target without `--next`, or build the project without lix (renamed the .haxerc to .haxerc_bac) haxe build.hxml, everything is working.

I miss something, or this is a known issue?

**Comment by serjek** [comment]
This issue is currently blocking lime with electron target as the template compiles both electron wrapper and application with single hxml.

**Comment by back2dos** [comment]
Should work now.
