### ISSUE TITLE
npx haxe doesn't exit with an error code

### ISSUE THREAD

**Issue by jcward** [lix-pm/haxeshim#47]
Apologies if this is the wrong project for this issue.

I'm trying to use lix locally via npx. This lack of an exit code was causing my vscode build task to "succeed", even when the build fails, which makes for a bad vscode experience - the "problems" tab is not populated, and the debug task is launched anyway, even though the build failed silently.

Observe:

```shell
cd /tmp/
mkdir zz
cd zz
echo "{}" > package.json
npm install lix
npx haxe -version  # installs stable / 4.0.2
echo "class Test { asdf }" > Test.hx
```
Ok, now that we're setup, we clearly expect that Test class not to compile:
```shell
npx haxe -cp . Test -js out.js && echo "yay"
# shows build errors
# echos yay, unfortunately
```
By contrast, haxe itself exits correctly:
```shell
haxe -cp . Test -js out.js && echo "yay"
# shows build errors
# Does NOT echo yay
```

**Comment by back2dos** [comment]
Works now, although there's some extra output.

**Comment by back2dos** [comment]
That's now dealt with as well.

**Comment by jcward** [comment]
:+1: Thanks!
