### ISSUE TITLE
Running haxe.cmd directly fails on cpp/java/cs

### ISSUE THREAD

**Issue by Gama11** [lix-pm/haxeshim#51]
Targets that have a post-compile `haxelib run` step fail to compile when calling `haxe.cmd` of a local lix installation directly (as vshaxe does for its tasks). Somehow it works through `npx` though:

```
> node_modules\.bin\haxe.cmd build.hxml
Error: Error: Library hxjava is not installed : run 'haxelib install hxjava'
Called from haxelib/client/Main.hx line 1222
Called from haxelib/client/Main.hx line 1424
Called from haxelib/client/Main.hx line 1456
Called from haxelib/client/Main.hx line 493

> npx haxe build.hxml
haxelib run hxjava hxjava_build.txt --haxe-version 4005 --feature-level 1
javac.exe "-sourcepath" "src" "-d" "obj" "-g" "@cmd"
```

I thought that it must be calling the wrong Haxelib in the first example, but explicitly putting it into the PATH doesn't help either:

```
set PATH=node_modules\.bin;%PATH%
```

So there must be some other difference. Could well be a Windows specific problem.

Related: https://community.haxe.org/t/vscode-with-lix-extension-compile-to-cpp/1826

**Comment by back2dos** [comment]
Ok, I found out how to make it work: when you set the PATH, be sure to make it absolute ;)

**Comment by Gama11** [comment]
Hmm... I could've sworn I tried that, but this might explain some things (such as me thinking that I had a working fix in vshaxe for a while... 🤦‍♂)
