### ISSUE TITLE
[mac] compiler server crash

### ISSUE THREAD

**Issue by kevinresol** [lix-pm/haxeshim#6]
First start a compilation server:
`haxe --wait 6000`

Then connect to it:
`haxe --connect 6000`

Then the server crashes with:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:51251
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
```

Note the port "51251" will be different every time.

**Comment by kevinresol** [comment]
And confirmed this doesn't happen on windows....

**Comment by kevinresol** [comment]
Problem identified:

It is because the listening server was not _yet_ up when the connection is created.

So I hacked it by inserting the following code just before `createConnection(port, '127.0.0.1')`

```js
while(require('child_process').spawnSync('lsof', ['-n',  '-iTCP:'+port], {stdio: 'ignore'}).status != 0) {}
```

The `lsof` command lists out the process that is listening on the given port and return 1 if there is none. So I loop until the server is up before making the connection.

**Comment by back2dos** [comment]
Wow, ok ^^

**Comment by back2dos** [comment]
Ok, well, so there's a test for this now which I got to pass on my bash for windows thingy. But travis says no. Initially this was related to neko being unavailable, but that's fixed: https://travis-ci.org/lix-pm/haxeshim/builds/233579067#L307

Can you confirm this fixes things for you locally?

**Comment by kevinresol** [comment]
yay I think it worked!
