### ISSUE TITLE
Uncaught exception - Could not find NekoAPI interface

### ISSUE THREAD

**Issue by endel** [lix-pm/haxeshim#65]
I'm trying to use `lix` along with `flixel`, but I'm having this issue:

```
 $ lix run lime build html5
Called from lime/_internal/backend/native/NativeCFFI.hx line 364
Called from lime/system/CFFI.hx line 198
Called from lime/system/CFFI.hx line 346
Uncaught exception - Could not find NekoAPI interface.
```

Any advice here? 
- Using macOS 10.14.3.
- Haxe 4.0.0-rc.2+77068e1

Here I can see the libneko files available under `~/haxe` directory. Not sure why they aren't picked up.

```
 $ find ~/haxe/ -name libneko.so
/Users/endel/haxe//haxe_libraries/hxcpp/4.0.8/haxelib/project/libs/nekoapi/bin/RPi/libneko.so
/Users/endel/haxe//haxe_libraries/hxcpp/4.0.8/haxelib/project/libs/nekoapi/bin/Linux/libneko.so
/Users/endel/haxe//haxe_libraries/hxcpp/4.0.8/haxelib/project/libs/nekoapi/bin/Linux64/libneko.so
```

```
 $ find ~/haxe/ -name libneko.dylib
/Users/endel/haxe//neko/libneko.dylib
/Users/endel/haxe//haxe_libraries/hxcpp/4.0.8/haxelib/project/libs/nekoapi/bin/Mac64/libneko.dylib
/Users/endel/haxe//haxe_libraries/hxcpp/4.0.8/haxelib/project/libs/nekoapi/bin/Mac/libneko.dylib
```

**Comment by Gama11** [comment]
>Yeah, hmm, the problem is that haxelib can pass libs to the compiler via `-L` and there's no equivalent in the public interface (that I know of).

Huh?

![](https://i.imgur.com/sQqbEpV.png)

**Comment by back2dos** [comment]
Yeah, native libs, i.e. ndlls: https://github.com/HaxeFoundation/haxe/blob/a56e3d14488e983fc1e7ef933b76dbbec5a44a40/src/compiler/haxe.ml#L143

This functionality was never publicly exposed and to make matters worse, it is now shadowed \o/

**Comment by Gama11** [comment]
Wtf.. 😄
