### ISSUE TITLE
spawnSync throws EINVAL error on Windows

### ISSUE THREAD

**Issue by AlexHaxe** [lix-pm/haxeshim#75]
reported by a user on discord: they ran into an issue where Haxe server failed to start with a `EINVAL` in `spawnSync` (unfortunately they chose to post a screenshot). 

I don't have Windows running, so I can't reproduce currently. but after searching the web I came accross https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2 which means if `spawnSync` wants to execute a `*.cmd` file it has to also provide a `{shell: true}` option going forward otherwise it will fail with `EINVAL`.

**Comment by wartman** [comment]
For reference, this is the error I'm seeing pop up in VSCode when it tries to initialize the Haxe server:

```
Error starting Haxe server: spawnSync
C:/Users/_/AppData/Roaming/npm/haxe.cmd EINVAL
```

This only happens when the Lix extension is active. Compiling still seems to work fine, it's just completion that's broken.

This is running on Windows 10, although I imagine you'd see the same on 11.

**Comment by flipflophhj** [comment]
I have the same problem.
I put
"haxe.executable": "haxe",
in settings.json to work around it.

**Comment by AlexHaxe** [comment]
to add some context: people who have been reporting these issues have recently updated their vscode version, which probably packages one of the patched nodejs versions.

so downgrading vscode should also work.

**Comment by JonasSonn** [comment]
> to add some context: people who have been reporting these issues have recently updated their vscode version, which probably packages one of the patched nodejs versions.
> 
> so downgrading vscode should also work.

Confirmed: downgrading vscode works

**Comment by back2dos** [comment]
Ok, I've checked this and the main problem seems to be this: https://github.com/vshaxe/vshaxe/issues/635

Haxeshim itself actually always calls `.exe` files on Windows, so I'm inclined to believe this is not a haxeshim issue at all, but will keep this open to check again once the vshaxe issue is dealt with.

**Comment by AlexHaxe** [comment]
the error message should be gone with vshaxe release 2.32.1.
